name: FDTRMS
favicon: null
layout_spectrum: 0.91172
typography_spectrum: 0.28384
title: Fire Service e-Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3cfcc'
    - '#8c8479'
    - '#090909'
    - '#ca5f4d'
    - '#ffc538'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
