name: FDTRMS
favicon: null
layout_spectrum: 0.91172
typography_spectrum: 0.28384
title: Fire Service e-Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1218'
    - '#ffffff'
    - '#594939'
    - '#92785d'
    - '#b2ab98'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 1
purpose: []
