name: FDTRMS
favicon: null
layout_spectrum: 0.9482120680622756
typography_spectrum: 0.8593923626467586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9025763238314539
  lightness: 0.9493110035546124
  saturation: 0.9988110966514796
  rhythmicContrast: 0.5164266445208341
purpose: []
